apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: shopflow/notification-service:latest
          ports:
            - containerPort: 3004
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: shopflow-config
                  key: NOTIFICATION_SERVICE_PORT
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopflow-secrets
                  key: SMTP_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP